# Generated by Django 3.2.5 on 2021-08-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_is_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_online',
            new_name='is_block',
        ),
    ]
